### ISSUE TITLE
Problems when changing the parent node of an instantiated scene

### ISSUE THREAD

**Issue by PuKYC** [DigitallyTailored/Godot-Open-World-Database#12]
I have problems when I change the type of the parent node of the scene, for example, the scene will not unload after changing the type beyond the distance, or the scene will disappear after changing the type.

For example, an instantiated scene will not be uninstalled after changing the parent node of the instantiated scene in a video.

https://github.com/user-attachments/assets/9cd789ce-c909-4f63-85d4-da865c4b79f4

**Comment by DigitallyTailored** [comment]
Thank you for the detailed bug report and video!

I will look into this. The scene tree interaction is a bit problematic.

That said, an updated version of the addon was just released today with pretty significant changes that may be worth looking at. The version on the asset library is up-to-date now https://godotengine.org/asset-library/asset/4166

**Comment by DigitallyTailored** [comment]
I've just pushed a version to github which appears to fix the issue for me.

We watch for the node type now and recalculate the size accordingly.

BTW - kind of related - I don't know if it is obvious but if a node does not have a size or is size 0 then it will be set to always loaded (as otherwise it would never load!)

**Comment by PuKYC** [comment]
sorry,It still doesn't seem to be fixed, the problem still exists.

https://github.com/user-attachments/assets/04c62f35-f9ab-41a9-9f81-10adb6c953b3

**Comment by PuKYC** [comment]
Or just don't change the type of node in the editor

Because I found another bug about what happens when you change the node type in the editor

**Comment by DigitallyTailored** [comment]
I believe this is also fixed as pert #14 

Please let me know if this works for you as well and we can close these issues.
